### PR TITLE
Issue 01

### PR DESCRIPTION
**Pull request by HVFrancis**
This is just a start. I'm new to pytest (and unit testing in general -- it wasn't part of my formative education). Let me know what looks good and what needs improvement.

### CODE REVIEW

**Comment by Ben-Hampson** [comment]
Nice! Coincidentally I'm new to pytest and made a similar PR (#32), haha! 

I like your use of 2 example GaugeSwatches.

**Review by terriko — CHANGES_REQUESTED** [review]
The changes I merged from @Ben-Hampson cause a file conflict with these ones, but you've got a couple of nice alternate tests in yours that I'd like to merge.  Do you mind resolving the conflict and adding your tests to the file I just merged?

**Comment by HVFrancis** [comment]
The two files have been combined. (But now when I run pytest I'm getting an error regarding pydantic. Not sure where that is coming from.)

**Comment by terriko** [comment]
Ah, pydantic is coming from the new type checking.  We added it to requirements.txt but unless you re-run `pip install -r requirements.txt` you wouldn't have gotten it.  Go ahead and install it and everything should work!  (As you can tell, it did work fine in the CI environment because it has it installed now)

**Review by terriko — APPROVED** [review]

**Pull request merged**
